const hre = require("hardhat");
const fs = require("fs");

async function main() {
    console.log("🚀 Deploying Real ZK Verifier...");

    // 1. Deploy AML Verifier (generated by snarkjs)
    // NOTE: SnarkJS names the contract 'Groth16Verifier'
    const AMLVerifier = await hre.ethers.getContractFactory("Groth16Verifier");
    const amlVerifier = await AMLVerifier.deploy();
    await amlVerifier.waitForDeployment();
    console.log("✅ AMLVerifier (Groth16Verifier) deployed to:", amlVerifier.target);

    // 2. Load existing AuditVerifier or deploy new one?
    // Since we need to link them, let's update the existing one or deploy a new "RealAuditVerifier"
    // For this demo, let's deploy a new AuditVerifier that uses the real ZK verifier

    const AuditVerifier = await hre.ethers.getContractFactory("AuditVerifier");
    const auditVerifier = await AuditVerifier.deploy(amlVerifier.target);
    await auditVerifier.waitForDeployment();
    console.log("✅ AuditVerifier (Real ZK) deployed to:", auditVerifier.target);

    // Save addresses
    const deploymentInfo = {
        MANTLE_SEPOLIA_CHAIN_ID: 5003,
        AML_VERIFIER_ADDRESS: amlVerifier.target,
        AUDIT_VERIFIER_ADDRESS: auditVerifier.target,
        TIMESTAMP: new Date().toISOString()
    };

    const deploymentPath = "deployments/zk_deployment.json";
    if (!fs.existsSync("deployments")) {
        fs.mkdirSync("deployments");
    }
    fs.writeFileSync(deploymentPath, JSON.stringify(deploymentInfo, null, 2));
    console.log(`📄 Deployment info saved to ${deploymentPath}`);

    // Verify contracts
    if (process.env.MANTLE_API_KEY) {
        console.log("🔍 Verifying contracts...");
        try {
            await hre.run("verify:verify", { address: amlVerifier.target });
        } catch (e) {
            console.log("Verification error (AMLVerifier):", e.message);
        }

        try {
            await hre.run("verify:verify", {
                address: auditVerifier.target,
                constructorArguments: [amlVerifier.target]
            });
        } catch (e) {
            console.log("Verification error (AuditVerifier):", e.message);
        }
    }
}

main().catch((error) => {
    console.error(error);
    process.exitCode = 1;
});
